### ISSUE TITLE
Script error : KeyError: 'consumption'

### ISSUE THREAD

**Issue by hot22shot** [amykyta3/envoy-logger#13]
Hello,

I'm trying to install this script and I have an issue, seems to be when the script try to collect data from the envoy:

```
root@unraid:~/test_envoy# python3 -m envoy_logger /mnt/user/appdata/envoy_logger/cfg.yaml
2024-07-25 16:20:44,241 INFO [cfg]: Loading config: /mnt/user/appdata/envoy_logger/cfg.yaml
2024-07-25 16:20:44,248 INFO [enphaseenergy]: Logging into enphaseenergy.com as myemail@gmail.com
2024-07-25 16:20:47,754 INFO [enphaseenergy]: Downloading new access token for envoy S/N: 1XXXXXXXXXXXX5
2024-07-25 16:20:48,137 INFO [enphaseenergy]: Caching token to: /root/.cache/enphase-envoy/1XXXXXXXXXXXX5.token
2024-07-25 16:20:49,031 INFO [envoy]: Logged into envoy. SessionID: Y---------------------------Z
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.9/site-packages/envoy_logger/__main__.py", line 32, in <module>
    S.run()
  File "/usr/lib64/python3.9/site-packages/envoy_logger/sampling_loop.py", line 38, in run
    data = self.get_sample()
  File "/usr/lib64/python3.9/site-packages/envoy_logger/sampling_loop.py", line 63, in get_sample
    data = envoy.get_power_data(self.cfg.envoy_url, self.session_id)
  File "/usr/lib64/python3.9/site-packages/envoy_logger/envoy.py", line 47, in get_power_data
    data = model.SampleData(json_data, ts)
  File "/usr/lib64/python3.9/site-packages/envoy_logger/model.py", line 83, in __init__
    for consumption_data in data['consumption']:
KeyError: 'consumption'
```

I also tried @jasonajack fork and I got a similar issue:

```
2024-07-25 16:38:59,481 INFO [config]: Loading config /etc/envoy_logger/config.yml for influxdb database
2024-07-25 16:39:00,000 INFO [enphaseenergy]: Logging into enphaseenergy.com as myemail@gmail.com
2024-07-25 16:39:02,089 INFO [enphaseenergy]: Downloading new access token for envoy S/N: 1XXXXXXXXXXXX5
2024-07-25 16:39:03,125 INFO [envoy]: Logged into envoy. SessionID: W-----------------------------O
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/envoy_logger/envoy_logger/__main__.py", line 4, in <module>
    main()
  File "/opt/envoy_logger/envoy_logger/cli.py", line 55, in main
    sampling_loop.run()
  File "/opt/envoy_logger/envoy_logger/influxdb_sampling_engine.py", line 37, in run
    self._collect_samples()
  File "/opt/envoy_logger/envoy_logger/influxdb_sampling_engine.py", line 40, in _collect_samples
    power_data, inverter_data = self.collect_samples_with_retry()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envoy_logger/envoy_logger/sampling_engine.py", line 44, in collect_samples_with_retry
    power_data = self.get_power_data()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envoy_logger/envoy_logger/sampling_engine.py", line 64, in get_power_data
    return self.envoy.get_power_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envoy_logger/envoy_logger/envoy.py", line 70, in get_power_data
    return SampleData.create(sample_data=json_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envoy_logger/envoy_logger/model.py", line 89, in create
    for consumption_data in sample_data["consumption"]:
                            ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'consumption'
```

I think it is because my installation does not include a consumption module, it only reports production energy.
Any idea to bypass that ?

**Comment by jasonajack** [comment]
@hot22shot It should be straightforward. I believe the correct way to do this is bypass parsing "consumption" field if it is not present.

I have a PR with some additional unit tests: https://github.com/jasonajack/envoy-logger/pull/1

Can you try this branch in your local environment and see if it works?

https://github.com/jasonajack/envoy-logger/tree/no_consumption

**Comment by hot22shot** [comment]
Thanks @jasonajack for your help ! I did test the branch.
I had one measurement in influxdb yesterday (with all the inverters) but nothing from my tests today.
There is still some error in the logs :

```
2024-07-27 09:18:05,657 INFO [config]: Loading config /etc/envoy_logger/config.yml for influxdb database
2024-07-27 09:18:10,000 INFO [enphaseenergy]: Logging into enphaseenergy.com as myemail@gmail.com
2024-07-27 09:18:12,014 INFO [enphaseenergy]: Downloading new access token for envoy S/N: 1XXXXXXXXXX5
2024-07-27 09:18:12,567 INFO [envoy]: Logged into envoy. SessionID: jnXXXXXXXXXXXXXXX
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/envoy_logger/envoy_logger/__main__.py", line 4, in <module>
    main()
  File "/opt/envoy_logger/envoy_logger/cli.py", line 55, in main
    sampling_loop.run()
  File "/opt/envoy_logger/envoy_logger/influxdb_sampling_engine.py", line 37, in run
    self._collect_samples()
  File "/opt/envoy_logger/envoy_logger/influxdb_sampling_engine.py", line 40, in _collect_samples
    power_data, inverter_data = self.collect_samples_with_retry()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envoy_logger/envoy_logger/sampling_engine.py", line 44, in collect_samples_with_retry
    power_data = self.get_power_data()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envoy_logger/envoy_logger/sampling_engine.py", line 64, in get_power_data
    return self.envoy.get_power_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envoy_logger/envoy_logger/envoy.py", line 70, in get_power_data
    return SampleData.create(sample_data=json_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envoy_logger/envoy_logger/model.py", line 114, in create
    total_production=total_production,
                     ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'total_production' where it is not associated with a value
```

**Comment by jasonajack** [comment]
This may be difficult unless I can see what sample data is coming from your envoy. I've added some debug logging in my branch. Can you git pull that branch and run the launcher with `LOG_LEVEL=debug ./launcher.sh ...`?

Look for a line starting with `DEBUG [sampling_engine]: Creating sample data from`

**Comment by hot22shot** [comment]
Here it is.
I have 14 inverters, wNow is at 0 because it was late when I tested.

```
2024-07-27 22:31:35,000 DEBUG [envoy]: Fetching power data
2024-07-27 22:31:35,777 DEBUG [model]: Creating sample data from: {
  "production": [
    {
      "type": "inverters",
      "activeCount": 14,
      "readingTime": 1722112132,
      "wNow": 0,
      "whLifetime": 1050203
    }
  ],
  "storage": [
    {
      "type": "acb",
      "activeCount": 0,
      "readingTime": 0,
      "wNow": 0,
      "whNow": 0,
      "state": "idle"
    }
  ]
}
2024-07-27 22:31:35,778 DEBUG [envoy]: Fetching inverter data
2024-07-27 22:31:36,050 DEBUG [sampling_engine]: Sampled power data:
{
 "net_consumption": {
  "eim_line_samples": []
 },
 "total_consumption": {
  "eim_line_samples": []
 },
 "total_production": {
  "eim_line_samples": []
 }
}
2024-07-27 22:31:36,050 DEBUG [sampling_engine]: Sampled inverter data:
{}
```

**Comment by jasonajack** [comment]
Interesting. It is reporting inverter count but no line data. I added
default values to include empty lists of line data by default. Are you
still seeing the exception in the logs?

**Comment by hot22shot** [comment]
No exception in the logs.

**Comment by jasonajack** [comment]
It could be your config. Setting up your config file can be tricky. Make sure you have it correctly configured. e.g.

```
---

enphaseenergy:
  email: youremail@gmail.com
  password: yourenphasepassword

envoy:
  serial: 123456789012
  url: https://yourenvoyurl

  # Give your envoy a name.
  # All points logged will be tagged with "source=<tag>"
  # Useful if you have multiple envoys
  tag: power-meter

influxdb:
  url: http://yourinfluxdburl
  token: yourtoken
  org: homelab
  bucket_hr: envoy_high_rate
  bucket_lr: envoy_low_rate

prometheus:
  listening_port: 3030

inverters:
  # "x": 350,
  # "y": 100,
  "123456789012":
    tags:
      row: 2
      col: 8
  # "x": 250,
  # "y": 100,
  "234567890123":
    tags:
      row: 2
      col: 7

  ...
```

If the inverter ids are incorrect it might not be finding the right data. Or if something is misconfigured in envoy you might not be able to see the inverter data.

**Comment by hot22shot** [comment]
I confirmed the inverters serial number with the array_layout_x.json file I got from the enlighten web interface.
I think my config file is simple :

```
# Config file for envoy-logger

# Your login info for enphaseenergy.com
enphaseenergy:
  email: myemail@gmail.com
  password: "mypassword"

# Information about your specific Envoy instance.
# https://enlighten.enphaseenergy.com will report the serial number under the "IQ-Gateway" information
envoy:
  serial: 1myenvoyserialnumber5
  url: https://192.168.1.20 #envoy has a fix IP

  # Give your envoy a name.
  # All points logged will be tagged with "source=<tag>"
  # Useful if you have multiple envoys
  tag: envoy

# How to access InfluxDB
influxdb:
  url: http://192.168.1.9:8086
  token: 2mygrafanatoken=
  org: Mxxxxxxn

  # Which InfluxDB bucket to send measurements.
  # This can be useful to control different data-retention rules
  # alternatively use the "bucket" key if you want everything to be sent to the
  # same bucket
  # bucket_hr: enphase_hr
  # bucket_lr: enphase_lr
  bucket: enphase

# Since the Envoy only tracks panel-level inverter production by serial number,
# it can be useful to provide InfluxDB measurements with additional tags that
# further describe your panels. This is completely optional, but can be useful
# metadata for your dashboard.
# You can figure out which inverter is which by logging into https://enlighten.enphaseenergy.com/
# and viewing: https://enlighten.enphaseenergy.com/pv/systems/<account number>/array_layout_x.json
# This will contain the X/Y coordinates of each inverter/panel.
# Since my layout is pretty simple, I chose to tag them with simple row/column numbers.
# Up to you to define a labeling scheme that works for you.
inverters:
  "4XXXXXXXXXX8":
    tags:
      row: 1
      col: 1
  "4XXXXXXXXXX8":
    tags:
      row: 1
      col: 2
  "4XXXXXXXXXX8":
    tags:
      row: 1
      col: 3
  "4XXXXXXXXXX8":
    tags:
      row: 1
      col: 4
  "4XXXXXXXXXX8":
    tags:
      row: 1
      col: 5
  "4XXXXXXXXXX8":
    tags:
      row: 1
      col: 6
  "4XXXXXXXXXX8":
    tags:
      row: 1
      col: 7
  "4XXXXXXXXXX8":
    tags:
      row: 2
      col: 1
  "4XXXXXXXXXX8":
    tags:
      row: 2
      col: 2
  "4XXXXXXXXXX8":
    tags:
      row: 2
      col: 3
  "4XXXXXXXXXX8":
    tags:
      row: 2
      col: 4
  "4XXXXXXXXXX8":
    tags:
      row: 2
      col: 5
  "4XXXXXXXXXX8":
    tags:
      row: 2
      col: 6
  "4XXXXXXXXXX8":
    tags:
      row: 2
      col: 7
```

In my latest test I used a fresh new bucket that was empty, I had a sample for all my inverters for 2024-07-28 16:20:24, I'll let the container run a while to see how it goes.

**Comment by jasonajack** [comment]
Glad to hear you got things resolved. I'll go ahead and cut a new release with the PR updates.

**Comment by hot22shot** [comment]
Thanks it's really helpful.
